### ISSUE TITLE
[FEATURE] 首頁 carousel

### ISSUE THREAD

**Issue by leon123858** [leon123858/ntuaf#2]
## 條列功能用例 Mary編輯
用戶看到自己有興趣的活動卡片, 點擊進入活動介紹頁面

## 概述功能
引用 https://www.npmjs.com/package/react-spring-3d-carousel 完成
內部放入基於 antd card 的 **活動簡介卡片** 組件
效果與介面參考連結
額外追加兩個按鈕, 切換近期與常設展, 利用 翻牌特效切換
It's use to show current activity and general exposition.

### UI/UX
![image](https://user-images.githubusercontent.com/56253942/209852987-6ff4c947-3e43-4f32-9163-62ecf88842ba.png)
![Screen Shot 2023-01-04 at 2 57 01 PM](https://user-images.githubusercontent.com/75064168/210500629-4d7b4404-55ef-4a75-a66e-cb84740ee065.png)

### 系統分析
提供吸引用戶查看展覽的介面, 且具有美美的動畫
此動畫為冷門動畫, 第三方組件少, 且客製化程度低, 
翻牌特效需原生完成, 可能難度高
預計參考以下教學: https://ithelp.ithome.com.tw/articles/10194451

### 系統設計
請完整描述要用到什麼下層元件, 與預期提供的介面(輸入/輸出參數)
若為低階實作需提供參數範例與偽代碼

內部包含 **活動簡介卡片**  和 Antd Button (事後可能客製化 btn)
應該包含兩個按鈕, 兩個 3d slide, 一個可以翻轉的 div, 
內部維護各卡片狀態, 需輸入參數如下
```json
{
  recent:[{
    image: string
    text: string
    id: string
  }],
  always:[{
    image: string
    text: string
    id:string
  }]
}
```
簡易偽代碼
```js
// interface
<HomeSlide data={}>
// implement
func (para) => {
  state <- 'recent' or 'always'
  return (
    <Btn onClick={set state to recent}>
    <Btn onClick={set state to always}>
    <翻轉 div class={依照state 切換}>
      <3d slide slides={list have para.recent in <IntroCard>}>
      <3d slide slides={list have para.always in <IntroCard>}>
    </>
  )
}
```
## 補充訊息
相依關係
**桌面路由** => 本組件 => **活動簡介卡片**

**Comment by ahueee** [comment]
carosuel尺寸：w241xh302
箭頭尺寸：22x21以內
