### ISSUE TITLE
[FEATURE] Google map box

### ISSUE THREAD

**Issue by leon123858** [leon123858/ntuaf#29]
## 條列功能用例
描述該功能可以被誰, 怎麼使用, 可以多列幾項

## 概述功能
用幾句話或專有名詞簡單說說要做什麼

### UI/UX
![image](https://user-images.githubusercontent.com/56253942/212532659-653eec68-4dc9-45b0-ba1c-61453401b99c.png)

### 系統分析
需求分析 + 可能面對的技術障礙

### 系統設計
請完整描述要用到什麼下層元件, 與預期提供的介面(輸入/輸出參數)
若為低階實作需提供參數範例與偽代碼
若為高階實作需提供 UML 圖

## 補充訊息
請描述組件相依關係, 與其他額外補充事宜

**Comment by leon123858** [comment]
介面可以設計一下, 舉例
<Map width="0.6vw" title="藝術家地圖" url="google map url" ><Map/>
想像一下, 你希望自己的組件怎麼被人使用 ?

**Comment by Cedricyu** [comment]
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3615.4727012957205!2d121.53607172695311!3d25.018027399999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3442a9898c33fb79%3A0x986a86f132e4eae4!2z5rS75aSn6aSQ5buz!5e0!3m2!1szh-TW!2stw!4v1674007111196!5m2!1szh-TW!2stw" width="600" height="450"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" title="myFrame"></iframe>


google 地圖的 iframe
