### ISSUE TITLE
[FEATURE] Art box

### ISSUE THREAD

**Issue by leon123858** [leon123858/ntuaf#34]
## 條列功能用例
描述該功能可以被誰, 怎麼使用, 可以多列幾項

## 概述功能
用幾句話或專有名詞簡單說說要做什麼

### UI/UX
![image](https://user-images.githubusercontent.com/56253942/212533719-e5501fe8-e74b-4814-8a99-1fcfca158b1c.png)
![image](https://user-images.githubusercontent.com/56253942/212533736-54f93c6c-86d0-4160-a8d5-41e9730f1fbb.png)

### 系統分析
需求分析 + 可能面對的技術障礙

import Heart from "react-heart"
antd card,imag

### 系統設計
請完整描述要用到什麼下層元件, 與預期提供的介面(輸入/輸出參數)
若為低階實作需提供參數範例與偽代碼
若為高階實作需提供 UML 圖

## 補充訊息
請描述組件相依關係, 與其他額外補充事宜

**Comment by Cedricyu** [comment]
`<ArtBox artName = "露娜" artist="諾克提斯" arturl = "https://wallpapercrafter.com/sizes/2048x1152/120189-Final-Fantasy-XV-video-games-Luna-Final-Fantasy-XV-Final-Fantasy.png"
			height ="10px" width = "30px" imageWidth = "300"
			/>`

**Comment by Cedricyu** [comment]
artName 作品名稱
artist 創作者名字
arturl 作品連結
height box 的高
width box 的寬
imageWidth 照片的寬
