### ISSUE TITLE
[ TASK ] 管理腳本開發

### ISSUE THREAD

**Issue by leon123858** [leon123858/ntuaf#45]
## 目標
支撐系統後端運作, 需每日執行, 或於特定場合執行的腳本

## 補充說明
應包含以下功能
1. 創建假資料以供前後端測試
2. 利用原始數據生成符合中間件定義格式的快取資料 詳見: 中間件 [cache.ts](https://github.com/leon123858/ntuaf/blob/main/middleware/ntuaf-sdk/src/utils/db/cache.ts) 的 method
3. 整理 artwork 中 like/unlike 的結果, 與進行彙整
4. 管理者行為
    - 創建新事件
    - 給予/移除用戶管理某事件的權利
    - 創建/刪除用戶
    - 刪除事件
    - 刪除投稿
    - (optional) 閱覽當日投稿
5. 一次性腳本
    - 大量匯入用戶(含權限設定)

**Comment by dsa66253** [comment]
Set Max number of event 
definition: in total of 10 events, kicking out regular events and containing the events in progress.
