### ISSUE TITLE
[FEATURE] Header

### ISSUE THREAD

**Issue by guan404ming** [leon123858/ntuaf#7]
## 條列功能用例
描述該功能可以被誰, 怎麼使用, 可以多列幾項

## 概述功能
用幾句話或專有名詞簡單說說要做什麼

### UI/UX
請放入 UI/UX 說明內容
並且回饋對 UI/UX 設計的意見與想法

### 系統分析
需求分析 + 可能面對的技術障礙

### 系統設計
請完整描述要用到什麼下層元件, 與預期提供的介面(輸入/輸出參數)
若為低階實作需提供參數範例與偽代碼
若為高階實作需提供 UML 圖

## 補充訊息
請描述組件相依關係, 與其他額外補充事宜

**Comment by leon123858** [comment]
這個先暫停一下, 因為 @dsa66253 做的 navi-bar 應該跟我和你說的 drawer 相同, 你們可能會在 RWD 機制上重疊, 這塊最好一個人做
