### ISSUE TITLE
[FEATURE] 關於我們 MemberTab

### ISSUE THREAD

**Issue by guan404ming** [leon123858/ntuaf#8]
## 條列功能用例
使用者可以在關於我們的頁面中，透過切換 tab 看到不同部門的人員。

## 概述功能
引用 antd 的 tab 組件，並根據輸入的資料，展示對應的人員清單

### UI/UX
![Screen Shot 2023-01-06 at 3 19 37 PM](https://user-images.githubusercontent.com/105915352/210950621-cbfc0bf3-7105-4749-bcdb-0f709227ee13.png)

### 系統分析
此組件核心需求是要讓使用者可以了解藝術季團隊組成:
1. UX - 應可切換不同 tab，來查看不同部門的人員
2. UI - 圖片大小及人員名稱字體大小都尚待確認

### 系統設計
僅使用 antd 的 Card 組建
為靜態組件，內部無 state
參數為工作人員資料, 預期需輸入資料來展示所有工作人員, 以下提供預期格式

```json
[
    {
        departmentName: '核心團隊',
        departmentImage: 'https://i.seadn.io/gcs/files/74e5cd691632cad888b4f615827ac5f2.png?auto=format',
        members: [
            {
                section: '總招',
                name: 'Theo',
            }
        ]
    }
]
```

## 補充訊息
請描述組件相依關係, 與其他額外補充事宜

**Comment by WenChen891004** [comment]
UI/UX 這邊對於排版以及職稱有變化，麻煩在幫忙修改ㄧ下

![Image](https://user-images.githubusercontent.com/121624175/212149029-56a55a53-e6ee-47cc-8c07-595458465b09.png)

目前已「設計部」為範例會這樣排版，以及職稱有改變！
